//! Typed TS binding generation via `tauri-specta`.
//!
//! Incremental migration: this module owns a `tauri-specta` `Builder`
//! populated with a *subset* of the existing `#[tauri::command]` functions
//! (those also annotated `#[specta::specta]`). The runtime keeps using
//! `tauri::generate_handler!` in `lib.rs` — Tauri-Specta is used here
//! purely for compile-time type generation.
//!
//! As more commands gain `#[specta::specta]` they should be added to
//! `collect_commands!` below; the generated `src/bindings.ts` will grow
//! accordingly without affecting the runtime invoke pipeline.

use crate::commands::{backup as backup_cmd, settings as set_cmd};

pub fn builder() -> tauri_specta::Builder<tauri::Wry> {
    tauri_specta::Builder::<tauri::Wry>::new().commands(tauri_specta::collect_commands![
        set_cmd::get_settings,
        set_cmd::save_settings,
        set_cmd::data_dir,
        backup_cmd::export_full_backup,
        backup_cmd::export_full_backup_to_path,
        backup_cmd::import_full_backup,
        backup_cmd::import_full_backup_from_path,
    ])
}

/// Export bindings to `src/bindings.ts`. Called from `run()` in debug
/// builds only, and from a `cargo test` entry point in CI.
#[cfg(debug_assertions)]
pub fn export_bindings() -> Result<(), String> {
    use specta_typescript::{BigIntExportBehavior, Typescript};

    let ts = Typescript::default()
        .bigint(BigIntExportBehavior::Number)
        .header(
            "// @generated by tauri-specta — do not edit by hand.\n\
             /* eslint-disable */\n\
             // @ts-nocheck\n",
        );

    builder()
        .export(ts, "../src/bindings.ts")
        .map_err(|e| format!("tauri-specta export failed: {e}"))
}

#[cfg(test)]
mod tests {
    #[test]
    fn export_typescript_bindings() {
        // Regenerates `src/bindings.ts`. Runs in CI via `cargo test`.
        super::export_bindings().expect("failed to export bindings");
    }
}
