// @generated by tauri-specta — do not edit by hand.
/* eslint-disable */
// @ts-nocheck

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async getSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSettings(settings: AppSettings) : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_settings", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dataDir() : Promise<string> {
    return await TAURI_INVOKE("data_dir");
},
async exportFullBackup() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_full_backup") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Writes the same payload as [`export_full_backup`] after the user picks a path in the UI.
 */
async exportFullBackupToPath(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_full_backup_to_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importFullBackup(args: ImportBackupArgs) : Promise<Result<ImportBackupResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_full_backup", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importFullBackupFromPath(args: ImportBackupFromPathArgs) : Promise<Result<ImportBackupResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_full_backup_from_path", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application-level settings persisted across launches. Values are stored as
 * JSON in a key/value table so we can evolve the schema freely without
 * migrations.
 */
export type AppSettings = { theme?: string; start_minimized?: boolean; launch_at_login?: boolean; auto_reconnect?: boolean; reconnect_delay_seconds?: number; 
/**
 * Cap on reconnect attempts before the supervisor gives up. `0` means
 * unlimited.
 */
max_reconnect_attempts?: number; 
/**
 * When true, a sleep/wake or network-change signal triggers an
 * immediate (out-of-band) reconnect without waiting for sshuttle to
 * time out on its own.
 */
reconnect_on_network_change?: boolean; kill_switch?: boolean; minimize_to_tray?: boolean; 
/**
 * `false` until the user has explicitly chosen between
 * "minimize to tray" and "quit" via the close-button dialog.
 * While `false`, clicking the window's close button shows that
 * dialog instead of doing anything immediately.
 */
close_action_chosen?: boolean; notifications?: boolean; debug_logging?: boolean; default_profile_id?: string | null; log_buffer_lines?: number; 
/**
 * When > 0 and a tunnel is connected, disconnect after this many
 * minutes without keyboard/mouse/scroll activity (UI thread heuristics).
 */
idle_disconnect_minutes?: number }
export type ImportBackupArgs = { json: string; 
/**
 * When false, all existing profiles are deleted before importing.
 */
mergeProfiles: boolean; 
/**
 * When true, replace app settings with those from the backup.
 */
applySettings: boolean }
export type ImportBackupFromPathArgs = { path: string; mergeProfiles: boolean; applySettings: boolean }
export type ImportBackupResult = { profilesWritten: number; settingsApplied: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
